### ISSUE TITLE
Add target identification

### ISSUE THREAD

**Issue by brombach** [swabhs/open-sesame#2]
I have trained the biLSTM model successfully, but it's not clear to me how I could use this on other data. Is there a way to input either a raw sentence or a simply tagged CoNLL file (Token, Lemma, POS) for tagging? `identify_frames` depends on the indexes of frame elements, which are available in the Framenet data, but not for an unseen sentence. Am I missing something obvious, like a method to achieve this?

**Comment by sammthomson** [comment]
Hi @brombach, Good point. This code so far is just enough to train and evaluate using gold targets; we need to add target identification. Most prior work uses a set of simple rules. We can probably rip them out of https://github.com/Noahs-ARK/semafor/blob/develop/src/main/java/edu/cmu/cs/lti/ark/fn/segmentation/RoteSegmenter.java pretty easily...

**Comment by brombach** [comment]
Thanks for the quick response, good to know I wasn't missing anything. The project looks great, and I had an f1 of .867 on the biLSTM model; I'll keep watching for this addition.

**Comment by bman7777** [comment]
Are there any new developments for target identification over the last year?  If not, can you recommend any other projects that are good at identifying frame targets?

Thank you!  Great work on this project so far!

**Comment by pradipcyb** [comment]
I trained the biLSTM model and tried to do frame prediction on unseen data. From raw text, I produced  Conll formatted data using Spacy NLP suite. Here is a sample:

1	Bob	_	bob	PROPN	NNP	2	_	_	_	_	_	_	_	O
2	bought	_	buy	VERB	VBD	2	_	_	_	_	_	_	_	O
3	an	_	an	DET	DT	4	_	_	_	_	_	_	_	O
4	apple	_	apple	NOUN	NN	2	_	_	_	_	_	_	_	O
5	.	_	.	PUNCT	.	2	_	_	_	_	_	_	_	O

1	He	_	-PRON-	PRON	PRP	3	_	_	_	_	_	_	_	O
2	then	_	then	ADV	RB	3	_	_	_	_	_	_	_	O
3	went	_	go	VERB	VBD	3	_	_	_	_	_	_	_	O
4	to	_	to	ADP	IN	3	_	_	_	_	_	_	_	O
5	a	_	a	DET	DT	6	_	_	_	_	_	_	_	O
6	market	_	market	NOUN	NN	4	_	_	_	_	_	_	_	O 


I have edited the frameid.py file to read this data in this format. But its not working and throwing an error 

`targetembs = [concatenate([fw_x[targetidx], bw_x[sentlen - targetidx - 1]]) for targetidx in targetpositions]
IndexError: list index out of range`

I think this is because the `identify_frames` method requires the target frame dictionary, which is obviously not in my Conll data. So my question  is there some way to provide the target dictionary to  `identify_frames` (maybe from the training set, but a code example is greatly appreciated ), or is there any better way you can provide to process raw text?

**Comment by swabhs** [comment]
I will add a module for target identification shortly.
