### ISSUE TITLE
Why do you block overlapping frame elements?

### ISSUE THREAD

**Issue by brenowca** [swabhs/open-sesame#20]
Hi @swabhs,

My question is not exactly an issue; it is more related to a modification I am performing on FrameNet data and how it fits in your code:

In those lines you raise an exception if there are any overlapping frame element annotations:

https://github.com/swabhs/open-sesame/blob/bd2a88e69d52e7284c4f4b95b3bd06f3e2c7e89a/sesame/xml_annotations.py#L112
and
https://github.com/swabhs/open-sesame/blob/bd2a88e69d52e7284c4f4b95b3bd06f3e2c7e89a/sesame/xml_annotations.py#L121

I am working on a data augmentation strategy that would add some overlapping frame element annotations (from different frames). What happens if I lift this restriction and allow overlapping frame elements? Is there a way I can add those new annotations to the training data without running into any issues?

Thank you for your time :)

**Comment by sammthomson** [comment]
Hi @brenocarvalho,

It's totally fine to have frame elements that overlap if they are annotated for different frames. That happens all the time and should be no problem.

Is the problem that you are moving FEs from one frame into another frame, so that FEs now overlap within the same frame annotation? If so, yes, that will be a problem. The model makes a semi-Markov assumption within each frame, which disallows this. We made that assumption because it's true in the data and globally normalizing under that assumption improves F1. Changing that assumption would require pretty big changes to the model. It's very possible, it wouldn't be SegRNN anymore, it could actually be simpler. E.g. you could predict the span for each FE independently. But yeah, it would require you digging into the code and changing the model.

Hope that helps,
-Sam

**Comment by brenowca** [comment]
Hi @sammthomson !

Thank you for the quick feedback!

Yep, I made a mistake and added two overlapping annotations for two frame elements of the same frame.

Once again, thank you :)
