### ISSUE TITLE
Can the annotations in the LU files be used for training?

### ISSUE THREAD

**Issue by senthilcool** [swabhs/open-sesame#22]
Looks like only the fulltext annotations are used for training. There are many partial sentence annotations done as part of the Lexical Unit's (present in the lu directory). These are partial as only the relevant part for lu/frame is annotated and not all the frames in the sentence.

Can these partial annotations be used in training the models to get better results? Or will the partial annotations hamper the learning process.

**Comment by swabhs** [comment]
Hi Senthil,

Yes they can be. I have a flag `--exemplar` that you can use for training [frame identification](https://github.com/swabhs/open-sesame/blob/master/sesame/frameid.py#L18) and [argument identification](https://github.com/swabhs/open-sesame/blob/master/sesame/argid.py#L22) with LU (otherwise known as exemplar) annotations. However, in my experiments, I did not see a significant improvement with this additional data. 

A couple of other things you might keep in mind:

1. LU annotations cannot be used for target identification, since only a single target is annotated per sentence.
2. You will have to run [preprocessing](https://github.com/swabhs/open-sesame/blob/master/sesame/preprocess.py#L19) with the `--exemplar` flag too.
